#!perl
#
# this script converts vPlug log files to CW log files for use with tsdec
#
# it searches in vPlug file for lines like
# [05.01.2009 11:09:43] - ProgDVB4.72.6:ORF1 - DCW: 153159132245E4C004443BCAEE95240A
# [05.01.2009 11:09:53] - ProgDVB4.72.6:ORF1 - DCW: F18EEB4512B70C7D04443BCAEE95240A
# the DCW part contains even and odd control word. The cw that changes if printed out to cwl file
# 0 F1 8E EB 6A 12 B7 0C D5      # 11:09:53
# 

my $ver = "vPlug2cwl.pl V0.4";

my $outfileopen = 0;
my $outfilename = "";
my $infilename = "vPlugGUI.Log";
my $CW0 = undef;
my $CW1 = undef;
my $initialCW = undef;
my $CWcnt = 0;

sub cwstring{
   my($cw, $par, $time) = @_;
   my $byte4 = sprintf ("%02X",  (hex(substr($cw,0,2)) + hex(substr($cw,2,2))  + hex(substr($cw,4,2)))  & 0xFF );
   my $byte8 = sprintf ("%02X",  (hex(substr($cw,8,2)) + hex(substr($cw,10,2)) + hex(substr($cw,12,2)))  & 0xFF );
   my $r = join(' ', ($par, substr($cw,0,2),  substr($cw,2,2),  substr($cw,4,2),  $byte4,
                            substr($cw,8,2),  substr($cw,10,2), substr($cw,12,2), $byte8,"     # $time\n"));
   return $r;
}

print "$ver converts vPlug log files to CW log files for use with tsdec\n";
print "reading $infilename...\n";
open(V, "<$infilename") or die "cannot open \"$infilename\" for read access\n";

while(<V>) {
   # [05.01.2009 11:10:23] - ProgDVB4.72.6:ORF1 - DCW: E32AFF40D86927276464946BB16CF0ED
   if ( m/^\[(.+?) (.+?)\] - (.+?)\:(.+?) - DCW: ([0-9A-Fa-f]{16})([0-9A-Fa-f]{16})/)  {
      #print "1 $1  2 $2  3 $3  4 $4  5 $5  6 $6\n";
      if ($outfileopen eq 0) {
         $yy = substr($1,8,2);
         $mm = substr($1,3,2);
         $dd = substr($1,0,2);
         $h = substr($2,0,2);
         $m = substr($2,3,2);
         $s = substr($2,6,2);
         $outfilename = "$yy$mm$dd\_$h$m$s\_$4.CWL";
         open(C, ">$outfilename") or die "cannot open output file \"$outfilename\" for writing";
         $outfileopen = 1;
         print "writing $outfilename...\n";
         print C "# CW log file generated by $ver\n";
         print C "# vPlugGUI.Log recorded at $1 $2 by $3\n";
         print C "# service name: $4\n";
         print C "#\n";
         # the 1st two CW cannot be written until the 3rd is known -> 0,1,0,... or 1,0,1,... 
         $initialCW = 1;
         $initialTime = $2;
         $CW0 = $5;
         $CW1 = $6;
         $CWcnt = 2;
      }
      if ($CW0 ne $5) {
         if ($initialCW ne undef) {
            print C cwstring($CW0, 0, $initialTime);
            print C cwstring($CW1, 1, $initialTime);
            $initialCW = undef;
         }
         print C cwstring($5, 0, $2);
         $CW0 = $5;
         $CWcnt++;
      }
      if ($CW1 ne $6) {
         if ($initialCW ne undef) {
            print C cwstring($CW1, 1, $initialTime);
            print C cwstring($CW0, 0, $initialTime);
            $initialCW = undef;
         }
         print C cwstring($6, 1, $2);
         $CW1 = $6;
         $CWcnt++;
      }
   }
}
if ($outfileopen eq 1) {
   close(C);
   print "Done. $CWcnt CWs were written.\n";
}
close(V);
