#!/usr/bin/env python3
"""Build a coherent (encrypted.ts, cwl) pair from a plaintext transport stream.

Each segment of the plaintext is run through tsdec's own constant-control-word
encryption with a fresh key pair, and the key that was actually used is written
to a matching .cwl. Decrypting the result with that log must reproduce the
plaintext exactly, which is what tools/verify.py checks.

The TSC handling below is the fiddly part and is worth spelling out:

  performCCW() only touches packets that already carry the transport
  scrambling bit (0x80), and it picks the key half with

      csa_encrypt(pkt, GetPacketParity(pkt))

  where GetPacketParity is bit 6 of that same header byte. csa_encrypt() bails
  out immediately if bit 7 is set, so the input TSC must already be the value
  we want the output to be:

      input 0x80  (parity 0)  -> encrypts with the even key -> output TSC 2
      input 0xC0  (parity 1)  -> encrypts with the odd  key -> output TSC 3

  Setting only 0x40 leaves bit 7 clear, performCCW() skips the packet and it
  stays in the clear, which is why an earlier version of this script silently
  produced unencrypted segments.
"""

import argparse
import hashlib
import os
import random
import subprocess
import sys

PCKTSIZE = 188

# PAT, PMT, CAT, TDT, SIT and the null packet are never scrambled in practice.
PSI_PIDS = (0x0000, 0x0001, 0x0002, 0x0010, 0x0011, 0x0012, 0x0014, 0x1000, 0x1FFF)


def make_cw(rng):
    while True:
        cw = bytes(rng.randrange(256) for _ in range(8))
        if (cw[0] + cw[1] + cw[2]) % 256 == cw[3] and (cw[4] + cw[5] + cw[6]) % 256 == cw[7]:
            return cw


def ccw_string(even, odd):
    return " ".join("%02X" % b for b in even + odd)


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--plain", required=True, help="plaintext transport stream")
    ap.add_argument("-o", "--out", required=True, help="encrypted stream to produce")
    ap.add_argument("-c", "--cwl", required=True, help="control word log to produce")
    ap.add_argument("-t", "--tsdec", required=True, help="tsdec binary used as the CSA engine")
    ap.add_argument("-w", "--cwlen", type=int, default=400, help="packets per control word")
    ap.add_argument("-s", "--seed", type=int, default=99)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    raw = open(args.plain, "rb").read()
    npackets = len(raw) // PCKTSIZE

    outdir = os.path.dirname(os.path.abspath(args.out)) or "."
    seg_in = os.path.join(outdir, "_seg_in.ts")
    seg_out = os.path.join(outdir, "_seg_out.ts")

    if os.path.exists(args.out):
        os.remove(args.out)

    cwl = []
    parity = 0
    idx = 0
    while idx < npackets:
        n = min(args.cwlen, npackets - idx)
        even, odd = make_cw(rng), make_cw(rng)
        cwl.append((parity, even if parity == 0 else odd, idx))

        marked = bytearray()
        for off in range(0, n * PCKTSIZE, PCKTSIZE):
            p = bytearray(raw[idx * PCKTSIZE + off: idx * PCKTSIZE + off + PCKTSIZE])
            pid = ((p[1] & 0x1F) << 8) | p[2]
            afc = (p[3] >> 4) & 3
            if afc == 1 and pid not in PSI_PIDS:
                p[3] = (p[3] & 0x3F) | (0xC0 if parity else 0x80)
            marked += p

        with open(seg_in, "wb") as f:
            f.write(bytes(marked))

        r = subprocess.run([args.tsdec, "-e", ccw_string(even, odd),
                            "-i", seg_in, "-o", seg_out],
                           capture_output=True)
        if r.returncode != 0:
            sys.stderr.write(r.stderr.decode("utf-8", "replace"))
            raise SystemExit("tsdec -e failed at packet %d" % idx)

        with open(args.out, "ab") as out:
            out.write(open(seg_out, "rb").read())

        idx += n
        parity ^= 1

    for p in (seg_in, seg_out):
        if os.path.exists(p):
            os.remove(p)

    with open(args.cwl, "w") as f:
        f.write("# synthetic control word log, generated by tools/mk_test_pair.py\n")
        f.write("# seed=%d cwlen=%d packets=%d\n" % (args.seed, args.cwlen, npackets))
        for par, cw, pkt in cwl:
            f.write("%d %s  # packet %d\n" % (par, " ".join("%02X" % b for b in cw), pkt))

    if not args.quiet:
        print("wrote %s: %d packets, %d control words" % (args.out, npackets, len(cwl)))
        print("  encrypted sha=%s" % sha(args.out)[:32])
        print("  plaintext sha=%s" % sha(args.plain)[:32])


if __name__ == "__main__":
    main()
